name: "Security Static Analysis"

on:
  pull_request: {}
  workflow_dispatch: {}
  push:
    branches:
    - main
    - master
  schedule:
  - cron: '14 13 6 * *'
jobs:
  scan:
    name: "Security Static Analysis"
    runs-on: ubuntu-latest

    container:
      image: semgrep/semgrep

    # Skip any PR created by dependabot to avoid permission issues:
    if: (github.actor != 'dependabot[bot]')

    steps:
      - uses: actions/checkout@v4
      - run: semgrep ci
        env:
          SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
